myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
]

urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'
urlpatterns = [
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name='registrationForm'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome,name='home'),
    path('test-paper',testPaper,name='testpaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',testResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),

]

models.py
from django.db import models

class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()

views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import*
import random

def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())

def candidateRegistrationForm(request):
    res=render(request,'registration_form.html')
    return res
def candidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']  #dict of post name and keys are the form name attributes such as username,password,
      #checkif the user already existed
        if(len(Candidate.objects.filter(username=username))):
          userStatus=1
        else:
            candidate=Candidate()#we have made an object of the model
            candidate.username=username
            candidate.password=request.POST['password'] # it is the data that we are getting from the form
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2
    else:
     userStatus=3 #if the method that we are getting from the form is not of type post
    context={
        'userStatus':userStatus
     }
    res=render(request,'registration.html',context)
    return res
def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)#it will return the queryset matched with the specified attributes
        if len(candidate)==0:
            loginError="INVALID USERNAME OR PASSWORD"
            res=render(request,'login.html', {'loginError':loginError}) #here we have passed loginerror in the dictionary
        else:
            """login success we want to sustain the data until the logout then we make the session variables"""
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home")
            return res
    else:
        res=render(request,'login.html')
    return res
def candidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    else:
        res=render(request,'home.html')
    return res
def testPaper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login") 
    #fetch the question from the database table
    n=int(request.GET['n'])
    question_pool= list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render(request,'test_paper.html',context)
    return res
def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    total_attempt = 0
    total_right = 0
    total_wrong = 0
    qid_list =[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
              total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    points = (total_right-total_wrong)/(len(qid_list))*10
    #to store result in result table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    #update candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points =(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    res=HttpResponseRedirect("result")
    return res

def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")

    candidate=Candidate.objects.filter(username=request.session['username'])
    results= Result.objects.filter(username_id=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res
def showTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    #fetch result from the Result table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={'result':result}
    res=render(request,'show_result.html',context)
    return res
def logoutView(request):
    if 'name'  in request.session.keys():
        del request.session['username']
        del request.session['name']
        return HttpResponseRedirect("login")
# Create your views here.

templates/candidate_history.html
{%extends 'main.html' %}
{%block title%}OTS-candidate result history {%endblock title%}
{%block top%}
<a href="{% url 'OTS:home'%}">signup</a>
<a href="{%url 'OTS:logout'%}">login</a>
{%endblock%}
{%block content%}
<h1>your report card</h1>
<p>hi<span class="special"> {{candidate.name}}</span>,you have attempted in total<span class="special">{{candidate.test_attempted}} </span> tests and you have scored <span class="special">{{candidate.points}}</span>on the scale of 10</p>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {%for r in results%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

templates/home.html
{%extends 'main.html' %}
{%block title%} OTS-candidate ots homepage {%endblock title%}

{%block top%}
<a href="{% url 'OTS:home'%}">signup</a>
<a href="{%url 'OTS:logout'%}">logout</a>

{%endblock%}
{%block content%}
<h1>WELCOME{{request.session.name}},to your home page</h1><!-- previously we had made a login session variable and used here to display the name only-->
<div class="button-link">
    <a href="{%url 'OTS:testpaper'%}?n=1">Test of 1 question</a> <!--it will tell the number of question using  question mark and n variables-->
</div>
<div class="button-link">
    <a href="{%url 'OTS:testpaper'%}?n=3">Test of 3 question</a> <!--it will tell the number of question using  question mark and n variables-->
</div>
<div class="button-link">
    <a href="{%url 'OTS:testpaper'%}?n=5">Test of  5 question</a> <!--it will tell the number of question using  question mark and n variables-->
</div>
<div class="button-link">
    <a href="{%url 'OTS:testHistory'%}">test history</a> <!--it will tell the number of question using  question mark and n variables-->
</div>
{%endblock%}

templates/login.html
{%extends 'main.html' %}
{%block title%} OTS LOGIN-FORM {%endblock title%}
{%block top%}
<a href="{% url 'OTS:registrationForm'%}">signup</a>

{%endblock%}
{%block content%}
<div class="all-forms">
    {%if loginError%}
    <div class="error">
        {{loginError}} 
    </div>
    {%endif%}
    <form action="{%url 'OTS:login'%}" method="POST">
     {%csrf_token%}
        <div class="form-unit">
          <label for="username">Username</label>
           <input type="text" name="username">

        </div>
        <div class="form-unit">
            <label type="password">password</label>
            <input type="password" name="password">
        </div>
        <div class="form-unit">
            <input  id="submit btn btn-primary" type="submit" value="login">
            <input type="reset" value="clear">
        </div>
    </form>
    <div class="user">
    New user<a  href ="{% url 'OTS:registrationForm'%}">click here</a>
    </div>
</div>
{%endblock%}

templates/main.html
<!DOCTYPE html>

{%load static%}<!--custom template-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {% endblock %}</title>
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <link rel="stylesheet" href="{%static 'formstyle.css'%}">
    <link rel="stylesheet" href="{%static 'buttonstyle.css'%}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> -->
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>ONLINE TESTING SYSTEM</h1></div>
        <div class="menu">
            {%block top%}{%endblock%} 
        </div>
    </div>
    <div class="content">
        {%block content%}{%endblock%}
    </div>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
</body>
</html>

templates/registration.html
{%extends 'main.html' %}

{%block title%} OTS-REGISTRATION STATUS {%endblock title%}
{%block top%}
<a href="{% url 'OTS:registrationForm'%}">signup</a>
<a href="{%url 'OTS:login'%}">login</a>
{%endblock%}
{%block content%}
{%if userStatus == 1%}
    <div class="userStatus">
        Sorry,username already existed,please try different username.
        <a href="{% url 'OTS:registrationForm'%}">back to candidate registration form</a>
    </div>
{%elif userStatus == 2 %}
    <div class="userStatus">
     congratulation,user created successfully
     <a href="{%url 'OTS:login'%}">login</a>
    </div>
{%elif userStatus == 3 %}
    <div class="userStatus">
        oops!something went wrong
        <a href="{% url 'OTS:registrationForm'%}">signup</a>
    </div>
{% endif %}
{%endblock%}

templates/registration_form.html
{%extends 'main.html'%}

{%block title%} OTS registration form {%endblock%}

{%block top%}
<a href="{%url 'OTS:login'%}">login</a>

{%endblock%}

{%block content%}
<div class="all-forms">
<form action="{% url 'OTS:storeCandidate' %}" method="post">
    {% csrf_token%}
<label for="username">Username</label>
<input type="text" name="username">

<label for="name" >Name</label>
<input type="text" name="name">

<label for="gender">gender</label>
<input type="radio"name="gender">m<input type="radio" name="gender">f

<label type="password" >password</label>
<input type="password" name="password">

<input id="submit" type="submit" value="Submit">
<input type="reset" value="Clear">
</form>
   already have an account ,<a href="{%url'OTS:login'% }">click here</a>
</div>
{% endblock %}

templates/show_result.html
{%extends 'main.html' %}
{%block title%} OTS-TEST RESULT {%endblock title%}
{%block top%}
<a href="{% url 'OTS:home'%}">signup</a>
<a href="{%url 'OTS:logout'%}">logout</a>
{%endblock%}
{%block content%}
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {%for r in result%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

templates/test_paper.html
{%extends 'main.html' %}
{%block title%} OTS-TEST PAPER {%endblock title%}  
{%block top%}

{%endblock%}
{%block content%}
<form action="{% url 'OTS:calculateTest'%}" method="post">

    {%csrf_token%}<!--croos site request foregries-->
    {%for question in questions %}
    <div class="question">
      <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
      {{question.que}}   <!--this is the way to make template variable-->
    </div>
 <div class="options"><input type="radio" name="q{{question.qid}}"value="a">{{question.a}}</div>
 <div class="options"><input type="radio" name="q{{question.qid}}"value="b">{{question.b}}</div>
 <div class="options"><input type="radio" name="q{{question.qid}}"value="c">{{question.c}}</div>
 <div class="options"><input type="radio" name="q{{question.qid}}"value="d">{{question.d}}</div>
 {%endfor%}
 <div><input id="submit"type="submit" value="submit"></div>
</form>
{%endblock%}

templates/welcome.html
{%extends 'main.html' %}
{%block title%} WELCOME TO ONLINE TESTING SYSTEM {%endblock title%}

{%block top%}
<a href="{% url 'OTS:registrationForm'%}">signup</a>
<a href="{%url 'OTS:login'%}">login</a>

{%endblock%}
{%block content%}
<p><span><h1 class="animate__animated animate__bounce" >Welcome to online  testing system<h1></span></p>
{%endblock%}